// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: proto/boids.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_CREATE RequestType = 0
	RequestType_UPDATE RequestType = 1
	RequestType_STOP   RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "STOP",
	}
	RequestType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"STOP":   2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_boids_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_boids_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_boids_proto_rawDescGZIP(), []int{0}
}

type BoidsSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=boids.RequestType" json:"type,omitempty"`
	Dimensions    *Vector2D              `protobuf:"bytes,2,opt,name=dimensions,proto3,oneof" json:"dimensions,omitempty"`
	NumberOfBoids int32                  `protobuf:"varint,3,opt,name=number_of_boids,json=numberOfBoids,proto3" json:"number_of_boids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoidsSessionRequest) Reset() {
	*x = BoidsSessionRequest{}
	mi := &file_proto_boids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoidsSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoidsSessionRequest) ProtoMessage() {}

func (x *BoidsSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoidsSessionRequest.ProtoReflect.Descriptor instead.
func (*BoidsSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_boids_proto_rawDescGZIP(), []int{0}
}

func (x *BoidsSessionRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_CREATE
}

func (x *BoidsSessionRequest) GetDimensions() *Vector2D {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BoidsSessionRequest) GetNumberOfBoids() int32 {
	if x != nil {
		return x.NumberOfBoids
	}
	return 0
}

type Vector2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2D) Reset() {
	*x = Vector2D{}
	mi := &file_proto_boids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2D) ProtoMessage() {}

func (x *Vector2D) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2D.ProtoReflect.Descriptor instead.
func (*Vector2D) Descriptor() ([]byte, []int) {
	return file_proto_boids_proto_rawDescGZIP(), []int{1}
}

func (x *Vector2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BoidFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNo       int64                  `protobuf:"varint,1,opt,name=frame_no,json=frameNo,proto3" json:"frame_no,omitempty"`
	MsgNo         int32                  `protobuf:"varint,2,opt,name=msg_no,json=msgNo,proto3" json:"msg_no,omitempty"`
	MsgOf         int32                  `protobuf:"varint,3,opt,name=msg_of,json=msgOf,proto3" json:"msg_of,omitempty"`
	Timestmap     float64                `protobuf:"fixed64,4,opt,name=timestmap,proto3" json:"timestmap,omitempty"`
	Boids         []*Boid                `protobuf:"bytes,5,rep,name=boids,proto3" json:"boids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoidFrame) Reset() {
	*x = BoidFrame{}
	mi := &file_proto_boids_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoidFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoidFrame) ProtoMessage() {}

func (x *BoidFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boids_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoidFrame.ProtoReflect.Descriptor instead.
func (*BoidFrame) Descriptor() ([]byte, []int) {
	return file_proto_boids_proto_rawDescGZIP(), []int{2}
}

func (x *BoidFrame) GetFrameNo() int64 {
	if x != nil {
		return x.FrameNo
	}
	return 0
}

func (x *BoidFrame) GetMsgNo() int32 {
	if x != nil {
		return x.MsgNo
	}
	return 0
}

func (x *BoidFrame) GetMsgOf() int32 {
	if x != nil {
		return x.MsgOf
	}
	return 0
}

func (x *BoidFrame) GetTimestmap() float64 {
	if x != nil {
		return x.Timestmap
	}
	return 0
}

func (x *BoidFrame) GetBoids() []*Boid {
	if x != nil {
		return x.Boids
	}
	return nil
}

type Boid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Vector2D              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Vel           *Vector2D              `protobuf:"bytes,2,opt,name=vel,proto3" json:"vel,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boid) Reset() {
	*x = Boid{}
	mi := &file_proto_boids_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boid) ProtoMessage() {}

func (x *Boid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boids_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boid.ProtoReflect.Descriptor instead.
func (*Boid) Descriptor() ([]byte, []int) {
	return file_proto_boids_proto_rawDescGZIP(), []int{3}
}

func (x *Boid) GetPos() *Vector2D {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Boid) GetVel() *Vector2D {
	if x != nil {
		return x.Vel
	}
	return nil
}

func (x *Boid) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_boids_proto protoreflect.FileDescriptor

const file_proto_boids_proto_rawDesc = "" +
	"\n" +
	"\x11proto/boids.proto\x12\x05boids\"\xaa\x01\n" +
	"\x13BoidsSessionRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.boids.RequestTypeR\x04type\x124\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\v2\x0f.boids.Vector2DH\x00R\n" +
	"dimensions\x88\x01\x01\x12&\n" +
	"\x0fnumber_of_boids\x18\x03 \x01(\x05R\rnumberOfBoidsB\r\n" +
	"\v_dimensions\"&\n" +
	"\bVector2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\x95\x01\n" +
	"\tBoidFrame\x12\x19\n" +
	"\bframe_no\x18\x01 \x01(\x03R\aframeNo\x12\x15\n" +
	"\x06msg_no\x18\x02 \x01(\x05R\x05msgNo\x12\x15\n" +
	"\x06msg_of\x18\x03 \x01(\x05R\x05msgOf\x12\x1c\n" +
	"\ttimestmap\x18\x04 \x01(\x01R\ttimestmap\x12!\n" +
	"\x05boids\x18\x05 \x03(\v2\v.boids.BoidR\x05boids\"\\\n" +
	"\x04Boid\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.boids.Vector2DR\x03pos\x12!\n" +
	"\x03vel\x18\x02 \x01(\v2\x0f.boids.Vector2DR\x03vel\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id*/\n" +
	"\vRequestType\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\b\n" +
	"\x04STOP\x10\x022J\n" +
	"\x05Boids\x12A\n" +
	"\rStreamSession\x12\x1a.boids.BoidsSessionRequest\x1a\x10.boids.BoidFrame(\x010\x01B%Z#github.com/ZephroC/zeph-boids/protob\x06proto3"

var (
	file_proto_boids_proto_rawDescOnce sync.Once
	file_proto_boids_proto_rawDescData []byte
)

func file_proto_boids_proto_rawDescGZIP() []byte {
	file_proto_boids_proto_rawDescOnce.Do(func() {
		file_proto_boids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_boids_proto_rawDesc), len(file_proto_boids_proto_rawDesc)))
	})
	return file_proto_boids_proto_rawDescData
}

var file_proto_boids_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_boids_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_boids_proto_goTypes = []any{
	(RequestType)(0),            // 0: boids.RequestType
	(*BoidsSessionRequest)(nil), // 1: boids.BoidsSessionRequest
	(*Vector2D)(nil),            // 2: boids.Vector2D
	(*BoidFrame)(nil),           // 3: boids.BoidFrame
	(*Boid)(nil),                // 4: boids.Boid
}
var file_proto_boids_proto_depIdxs = []int32{
	0, // 0: boids.BoidsSessionRequest.type:type_name -> boids.RequestType
	2, // 1: boids.BoidsSessionRequest.dimensions:type_name -> boids.Vector2D
	4, // 2: boids.BoidFrame.boids:type_name -> boids.Boid
	2, // 3: boids.Boid.pos:type_name -> boids.Vector2D
	2, // 4: boids.Boid.vel:type_name -> boids.Vector2D
	1, // 5: boids.Boids.StreamSession:input_type -> boids.BoidsSessionRequest
	3, // 6: boids.Boids.StreamSession:output_type -> boids.BoidFrame
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_boids_proto_init() }
func file_proto_boids_proto_init() {
	if File_proto_boids_proto != nil {
		return
	}
	file_proto_boids_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_boids_proto_rawDesc), len(file_proto_boids_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_boids_proto_goTypes,
		DependencyIndexes: file_proto_boids_proto_depIdxs,
		EnumInfos:         file_proto_boids_proto_enumTypes,
		MessageInfos:      file_proto_boids_proto_msgTypes,
	}.Build()
	File_proto_boids_proto = out.File
	file_proto_boids_proto_goTypes = nil
	file_proto_boids_proto_depIdxs = nil
}
